APDS9960 driver
Ocebots/ocebot-code-2024 pull request #36
Opened 2024-08-05 19:35 UTC by Archonic944

Yippee

- Enable the sensor
- Enable the proximity detection
- Set the proximity high and low threshold
- Set the proximity persistence filter
- Enable the proximity interrupts
- Clear the interrupts
- Disable the sensor

2024-08-05 19:45 UTC, BlueZeeKing requested changes
Everything but the port looks good

2024-08-05 19:45 UTC, BlueZeeKing commented on src/main/java/frc/utils/APDS9960.java
> +  I2C i2c = new I2C(I2C.Port.kOnboard, VisionConstants.APDS9960_I2C_ADDRESS);
It uses the MXP port, not the onboard one

2024-08-06 15:44 UTC, BlueZeeKing requested changes
Nice job catching the mistake with using setAndPreserve, but the port is still incorrect, and overwrite doesn't prevent other bits in the register from being modified.

2024-08-06 15:44 UTC, BlueZeeKing commented on src/main/java/frc/utils/APDS9960.java
> +    i2c.write(reg, (byte) ((read[0] & ~mask) | value));
You should also mask the value to ensure you're only writing to the bits in the mask

2024-08-06 15:48 UTC, Archonic944 commented
Mb, I  just assumed that anyone writing wasn't going to set bits outside of their mask

2024-08-07 14:05 UTC, BlueZeeKing commented
> Mb, I just assumed that anyone writing wasn't going to set bits outside of their mask

This *should* be a correct assumption, but people make mistakes and might accidentally write outside of the mask.

2024-08-07 19:46 UTC, BlueZeeKing approved these changes
LGTM

2024-08-16 19:14 UTC, merged